name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh

      - name: Authenticate with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 
        run: railway login --token $RAILWAY_TOKEN

      - name: Deploy to Railway
        run: railway up