name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Railway project link
        run: |
          mkdir -p .railway
          echo "${{ secrets.RAILWAY_PROJECT_ID }}" > .railway/linked_project

      - name: Deploy to Railway
        run: |
          npm install -g @railway/cli
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up --detach
